post:
  summary: Add a new project
  operationId: addProject
  requestBody:
    content:
      application/json:
        schema:
          $ref: ../../schemas/Project.yaml
    required: true
  responses:
    '200':
      description: Successful operation
      content:
        application/json:
          schema:
            $ref: ../../schemas/Project.yaml
    '405':
      description: Invalid input


